[physics_config]
dx = 0.5
dy = 0.5
dt = 1e-2
max_sim_time = 100000
temper0 = 0.5
temper1 = 0.8
rho_liq = 0.8
rho_vap = 2e-2
Tc = 1.0
aa = 1.0
w = 1.0
b = 1.0
zeta0 = 1.0
eta0 = 1.0
m = 1.0
lambda0 = 0.2

nb_col = 100
nb_row = 2

[initial_time_config]
n_liq = 40 # not used

[save_config]
directory_name = "defaultdir"
user_comment = "simulation made with default vdw config"
histo_freq = 50
histo_save = 100
num_bin = 100

[physics_constants]
kB = 0.2962962962962963
DeBroglie0 = 0.1
dim = 2
lambda_grad = 0.66