[physics_config]
x_size = 20
dx = 0.1
temper0 = 0.5
temper1 = 0.7
rho_liq = 0.8
rho_vap = 0.02
dt = 0.01

[initial_time_config]
n_liq = 40.0

[save_config]
directory_name = "test_simu"
user_comment = ""
histo_freq = 10000
histo_save = 10000
num_bin = 100
